### ISSUE TITLE
Adding new skill, industry, or course will default to 1st value in skills drop down.

### ISSUE THREAD

**Issue by schiemej** [jknox0122/Quaranteam#10]
Unless you change the industry or course value to something else other than the first value on the dropdown menu then change it back, the entry will default to the first value in the skills field (currently C++)

![image](https://user-images.githubusercontent.com/55607998/100533064-17055880-31b5-11eb-875c-d4f16881fd65.png)

![image](https://user-images.githubusercontent.com/55607998/100533077-38fedb00-31b5-11eb-87e1-22dd90a16d0e.png)

**Comment by GreatAmus** [comment]
Fixed this issue. It wasn't updating the reference when you changed categories.
