### ISSUE TITLE
Github link only shows repositories on the profile page

### ISSUE THREAD

**Issue by connorlunsford** [jknox0122/Quaranteam#14]
This isn't necessarily a bug and it is pretty low on our to do list if we are fixing bugs, but it is something that would be nice to implement if we were creating a full version of the website. The github link only shows the repository tooltip when you are on a specific profile. In our clients example, she explains that hovering over the link after searching should show the github repositories. So not really a bug, just a missed feature.

**Comment by jknox0122** [comment]
Gotcha. You are saying to have it hover over the experts page github links
as well?

John

**Comment by connorlunsford** [comment]
Yeah that's essentially what our client said in the week 2 video I think. Like I said it's definitely low priority as it doesn't hinder anything and would more be a quality of life feature rather than a bug to fix.

**Comment by jknox0122** [comment]
This has been resolved in latest commit
