### ISSUE TITLE
Github link in experts page doesn't work

### ISSUE THREAD

**Issue by GreatAmus** [jknox0122/Quaranteam#8]
Steps to reproduce:
1) Search of an expert
2) Click on the expert's github profile link
3) No redirect happens even though the expected behavior is to go to github

The link works fine if you are on the main experts page. Only doesn't work after searching for an expert

**Comment by jknox0122** [comment]
I’m pretty sure I fixed that in the latest push. Did you pull latest?

John

**Comment by GreatAmus** [comment]
I did. However, I fixed it in my latest push. Does that mean I can't count this as one of the bugs for HW5? I', still counting it :)

**Comment by GreatAmus** [comment]
Okay - instructor confirmed fixed bugs can count towards the three issues.
